spring:  main:    allow-circular-references: true  profiles:    active: smart    hr:  salary:    def:      percent: 5    special:       lessThanTwoAnHalfYears: 0      lessThanFiveMoreThanTwoAnHalfYears: 2      lessThanTenMoreThanFiveYears: 5      MoreThanTen: 10                            
    
 